[build]
  command = "rm -f .nvmrc && npm install && npm run build"
  publish = "dist"
  base = "my-app"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9.8.1"
  NODE_ENV = "production"
  CI = "false"
  NPM_CONFIG_LOGLEVEL = "verbose"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 