[build]
  command = "npm install -g npm@9.8.1 && npm ci && npm run build"
  publish = "dist"
  base = "my-app"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9.8.1"
  NODE_ENV = "production"
  CI = "false"
  NPM_CONFIG_LOGLEVEL = "verbose"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 