[build]
  command = "npm install && npm run build"
  publish = "dist"
  base = "my-app"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_VERSION = "9.8.1"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 