[build]
  command = "cd my-app && npm run build"
  publish = "my-app/dist"
  base = "my-app"

[build.environment]
  NODE_VERSION = "18.20.8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 