[build]
  command = "cd my-app && npm cache clean --force && rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "my-app/dist"
  base = "my-app"

[build.environment]
  NODE_VERSION = "18.20.8"
  NODE_ENV = "production"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 